package com.travelbank.knit.schedulers;

/**
 * Base interface for {@link Schedulers} and it's testing counterpart.
 * Used by {@link com.travelbank.knit.InternalModel}s generated by the KnitProcessor.
 * It provides instances for all schedulers available to Knit.
 *
 * @see AndroidMainThreadScheduler
 * @see ImmediateScheduler
 * @see IOScheduler
 * @see com.travelbank.knit.schedulers.heavy.HeavyTaskScheduler
 * @author Omer Ozer
 */

public interface SchedulerProvider {

    /**
     * Returns {@link IOScheduler}
     */
    SchedulerInterface io();

    /**
     * Returns {@link AndroidMainThreadScheduler}
     */
    SchedulerInterface main();

    /**
     * Returns {@link ImmediateScheduler}
     */
    SchedulerInterface immediate();

    /**
     * Returns {@link com.travelbank.knit.schedulers.heavy.HeavyTaskScheduler}
     */
    SchedulerInterface heavy();

    /**
     * Returns a {@link SchedulerInterface} associated with the given {@link KnitSchedulers}.
     */
    SchedulerInterface forType(KnitSchedulers type);
}
